# config for the database client
mysql_user: root
mysql_password: root
mysql_cert:
mysql_key:
mysql_rootCA:
mysql_defaults_file: config/my_development.cnf

# config for the rest client
rest_api: http://shift_shift_1:9195/api/v1/
rest_cert:
rest_key:

# general config
log_dir: /tmp/shift/
pt_osc_path: gh-ost
pending_drops_db:
enable_trash: true
log_sync_interval: 10
state_sync_interval: 10
stop_file_path: /tmp/stop_shift_runner

# optionally override the host/port/db to run an OSC on
host_override:
port_override:
database_override:
